name: cache

on:
  label:
    types: [edited]
    
jobs:
  run:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Cache freetds
        uses: actions/cache@v4
        with:
          path: ~/.cache/freetds-1.4.23
          key: ${{ runner.os }}-freetds-1.4.23
          restore-keys: |
            ${{ runner.os }}-freetds-1.4.23

      - name: Install freetds
        run: |
          sudo apt-get install libc6-dev
          wget http://www.freetds.org/files/stable/freetds-1.4.23.tar.gz
          tar -xzf freetds-1.4.23.tar.gz
          cd freetds-1.4.23
          ./configure --prefix=/usr/local --with-tdsver=7.4 --disable-odbc
          sudo make
          sudo make install

      - name: Print path
        run: |
          where freetds
